
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='antsibull',
    version='0.2.0',
    description='Tools for building the Ansible Distribution',
    python_requires='==3.*,>=3.6.0',
    project_urls={"repository": "https://github.com/ansible-community/antsibull"},
    author='Toshio Kuratomi',
    author_email='a.badger@gmail.com',
    license='GPL-3.0-or-later',
    entry_points={"console_scripts": ["antsibull-build = antsibull.cli.antsibull_build:main", "antsibull-changelog = antsibull.cli.antsibull_changelog:main", "antsibull-lint = antsibull.cli.antsibull_lint:main"]},
    packages=['antsibull', 'antsibull.changelog', 'antsibull.cli', 'antsibull.data', 'antsibull.schemas'],
    package_dir={"": "."},
    package_data={"antsibull.data": ["*.j2", "*.txt"]},
    install_requires=['aiofiles', 'aiohttp', 'docutils', 'jinja2', 'packaging', 'pydantic', 'pyyaml', 'rstcheck==3.*,>=3.0.0', 'semantic-version', 'sh'],
    extras_require={"dev": ["asynctest==0.*,>=0.13.0", "codecov==2.*,>=2.0.22", "cryptography==2.*,>=2.9.2", "flake8==3.*,>=3.8.0.a2", "mypy==0.*,>=0.770.0", "pylint==2.*,>=2.5.2", "pyre-check==0.*,>=0.0.46", "pytest==5.*,>=5.4.1", "pytest-asyncio>=0.12", "pytest-cov==2.*,>=2.8.1"]},
)
